---
title: "Онлайн-карта распределения госсредств на НКО"
subtitle: 'направление <br> "Лучшее визуальное представление"'
author: 'Г. Мороз (команда "42")'
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, center, middle

# Цели проекта

---

Получить и визуализировать на карте распределение госсредств на НКО по годам

--

- Граждане и организации, заинтересованные в получении информации об использовании бюджета

--

- Исследователи, аналитики в финансово-бюджетной сфере, учащиеся, ученые

--

- Чиновники, заинтересованные в выявлении ошибок, происходящий на этапе передачи данных от муниципалитета

---
class: inverse, center, middle

# Источник данных

---

Организаторы предоставили ссылки на два датасета

* дамп данных на сайте Открытые НКО https://openngo.ru/api-docs/ (json, 700 мб)
* датасет с доходами НКО (агрегированные данные, csv, 75 мб)

---
class: inverse, center, middle

# Результаты

---
class: middle

- Данные (64 468  строк) со следующими столбцами:
    - год
    - название организации
    - тип организации
    - код региона
    - название региона
    - сумма в миллионах рублей
    - тип государственной поддержки (контракты, субсидии, гранты, все вместе)
- Сайт с 50 картами (абсолютные значения и доли от всего бюджета)

---

class: center, middle

[Давайте посмотрим сайт!](https://agricolamz.github.io/2018_mosfindata_hackathon_4/01_tax.html)

---

class: center, middle

Спасибо за внимание!