```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
library(tidyverse)
library(leaflet)
library(mapview)
options(scipen = 999)
```
```{r results="asis"}
cat("
<style>
.leaflet-container {
    background: #FFF;
}
</style>
")
```
```{r}
selected <- "Контракты"
selected_t <- "contracts"
```

```{r}
s_year <- 2012
```
### **[2010](02_contracts_2010.html) [2011](02_contracts_2011.html) [2012](02_contracts_2012.html) [2013](02_contracts_2013.html) [2014](02_contracts_2014.html) [2015](02_contracts_2015.html) [2016](02_contracts_2016.html) [2017](02_contracts_2017.html)**

# `r s_year` `r selected`

```{r}
df <- read_csv("overall_dataset.csv")

df %>% 
  filter(gov_support_type == selected_t,
         year == s_year, 
         region_name == "Москва") %>% 
  group_by(region_code, region_name) %>% 
  summarise(sum_mln = sum(sum_mln)) ->
  moscow

df %>% 
  filter(gov_support_type == selected_t,
         year == s_year, 
         region_name == "Министерство юстиции") %>% 
  group_by(region_code, region_name) %>% 
  summarise(sum_mln = sum(sum_mln)) ->
  minyust

df %>% 
  filter(gov_support_type == selected_t,
         year == s_year, 
         region_name != "Москва",
         region_name != "Министерство юстиции") %>% 
  group_by(region_code, region_name) %>% 
  summarise(sum_mln = sum(sum_mln)) %>% 
  ungroup() %>% 
  mutate(ratio = sum_mln/sum(sum_mln)) ->
  df

ru <- geojsonio::geojson_read("russia.geojson", what = "sp")

ru@data %>% 
  left_join(df) ->
  ru@data

pal_1 <- colorNumeric(c("white", "navy"), NULL)
pal_2 <- colorNumeric(c("white", "darkgreen"), NULL)

m1 <- leaflet(ru) %>% 
  addPolygons(stroke = TRUE,
              color = "black",
              weight = 1,
              smoothFactor = 0.3, 
              fillOpacity = 1,
              fillColor = ~pal_1(ru@data$sum_mln),
              label = ~paste0(ru@data$NAME_1,
                              ": ", 
                              format(round(ru@data$sum_mln, 4), big.mark = " "), " млн. р.")) %>%
  addLegend(pal = pal_1, 
            values = ru@data$sum_mln,
            labFormat = labelFormat(suffix = " млн. р."))

m2 <- leaflet(ru) %>% 
  addPolygons(stroke = TRUE,
              color = "black",
              weight = 1,
              smoothFactor = 0.3, 
              fillOpacity = 1,
              fillColor = ~pal_2(ru@data$ratio),
              label = ~paste0(ru@data$NAME_1,
                              ": ", 
                              round(ru@data$ratio*100, 4), "%")) %>%
  addLegend(pal = pal_2, 
            values = ru@data$ratio*100,
            labFormat = labelFormat(suffix = "%"))

mapview::sync(m1, m2)
```
<br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br>

### В Москве --- `r format(round(moscow$sum_mln), big.mark = " ")` млн. р.
### Не аффилиировано ни с каким регионом --- `r format(round(minyust$sum_mln), big.mark = " ")` млн. р.
